name: Biuld and Deploy 
on:
   push: 
       branches:
            - master
      workflow_dispatch:
          
      permissions:
        contents: write
jobs:
   biuld-and-deploy:
   runs-on: ubuntu_latest
     steps:
   - name: Checkout Repository
     uses: action/checkout@v3

   - name: Install and Build
   run:|
   npm ci
   npm run build
  name: Deploy
  uses: JamesIves/github-pages-deploy-action@v4
  with:
  folder: dist/prueba-de-angular #aqui nombre de la app
